FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-dev \
    libssl-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

WORKDIR /app/pqc/build
RUN cmake .. && make

WORKDIR /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "main.py"]
